version: '3.0'
services:
  app:
    image: wallodya/todo_back
    labels:
      - com.docker.compose.container-number=1
    build: 
      dockerfile: Dockerfile
      context: .
      target: app_dev
    volumes:
      - ./:/var/www/app
    ports:
      - "80:3000"
    depends_on:
      - psql
    command: npm run start:dev
    env_file:
      - ./env/.development.env
  
  prod_build:
    build: 
      dockerfile: Dockerfile
      context: .
      target: app_prod
    volumes:
      - ./:/var/www/app
    ports:
      - "80:3000"
    depends_on:
      - psql
    command: npm run start:prod
    env_file:
      - ./env/.development.env

  psql:
    image: postgres:15
    labels:
      - com.docker.compose.container-number=2
    env_file:
      - ./env/.development.env 
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

volumes:
  db: