version: '3.0'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - psql
    command: npm run start:dev

  psql:
    image: postgres:15
    env_file:
      - ./env/.development.env 
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

volumes:
  db: