version: '3.0'
services:
  app:
    image: node:18-alpine
    command: npm i && npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:12
    env_file: 
      - ./env/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 54320:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

volumes:
  db: